stages:
  - build
  - run

image: gitlab.com:1234/patch/for/image:1.0 

.docker_login: &docker_login
  - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$DOCKERHUB_USERNAME\",\"password\":\"$DOCKERHUB_PASSWORD\"}}}" > /kaniko/.docker/config.json

.kaniko_build: &kaniko_build
  - |
    /kaniko/executor \
    --context "${CI_PROJECT_DIR}" \
    --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
    --no-push

hk_panel_test:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  before_script: *docker_login
  variables:
    IMAGE_NAME: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/hk_panel_test
    IMAGE_TAG: ${CI_COMMIT_TAG:-latest}
  script:
    - *kaniko_build
  allow_failure: false
  tags:
    - docker_blabla

run_hk_server_test:
  stage: run
  image: golang:1.21
  script:
    - go run main.go -action start_console
    - go run main.go -action stop_console
  tags:
    - docker_blabla
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_TYPE == "test"'
      when: on_success
    - when: never

run_hk_server_power:
  stage: run
  image: golang:1.21
  script:
    - go run main.go -action start_power
  tags:
    - docker_blabla
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_TYPE == "power"'
      when: on_success
    - when: never

